import Card from "./Card";

const cards = [
  new Card(0, "0 The Fool"),
  new Card(1, "I The Magician"),
  new Card(2, "II The High Priestess"),
  new Card(3, "III The Empress"),
  new Card(4, "IV The Emperor"),
  new Card(5, "V The Hierophant"),
  new Card(6, "VI The Lovers"),
  new Card(7, "VII The Chariot"),
  new Card(8, "VIII Strength"),
  new Card(9, "IX The Hermit"),
  new Card(10, "X The Wheel of Fortune"),
  new Card(11, "XI Justice"),
  new Card(12, "XII The Hanged Man"),
  new Card(13, "XIII Death"),
  new Card(14, "XIV Temperance"),
  new Card(15, "XV The Devil"),
  new Card(16, "XVI The Tower"),
  new Card(17, "XVII The Star"),
  new Card(18, "XVIII The Moon"),
  new Card(19, "XIX The Sun"),
  new Card(20, "XX Judgement"),
  new Card(21, "XXI The World"),
  new Card(22, "Ace", "Wands"),
  new Card(23, "Two", "Wands"),
  new Card(24, "Three", "Wands"),
  new Card(25, "Four", "Wands"),
  new Card(26, "Five", "Wands"),
  new Card(27, "Six", "Wands"),
  new Card(28, "Seven", "Wands"),
  new Card(29, "Eight", "Wands"),
  new Card(30, "Nine", "Wands"),
  new Card(31, "Ten", "Wands"),
  new Card(32, "Page", "Wands"),
  new Card(33, "Knight", "Wands"),
  new Card(34, "Queen", "Wands"),
  new Card(35, "King", "Wands"),
  new Card(36, "Ace", "Cups"),
  new Card(37, "Two", "Cups"),
  new Card(38, "Three", "Cups"),
  new Card(39, "Four", "Cups"),
  new Card(40, "Five", "Cups"),
  new Card(41, "Six", "Cups"),
  new Card(42, "Seven", "Cups"),
  new Card(43, "Eight", "Cups"),
  new Card(44, "Nine", "Cups"),
  new Card(45, "Ten", "Cups"),
  new Card(46, "Page", "Cups"),
  new Card(47, "Knight", "Cups"),
  new Card(48, "Queen", "Cups"),
  new Card(49, "King", "Cups"),
  new Card(50, "Ace", "Swords"),
  new Card(51, "Two", "Swords"),
  new Card(52, "Three", "Swords"),
  new Card(53, "Four", "Swords"),
  new Card(54, "Five", "Swords"),
  new Card(55, "Six", "Swords"),
  new Card(56, "Seven", "Swords"),
  new Card(57, "Eight", "Swords"),
  new Card(58, "Nine", "Swords"),
  new Card(59, "Ten", "Swords"),
  new Card(60, "Page", "Swords"),
  new Card(61, "Knight", "Swords"),
  new Card(62, "Queen", "Swords"),
  new Card(63, "King", "Swords"),
  new Card(64, "Ace", "Pentacles"),
  new Card(65, "Two", "Pentacles"),
  new Card(66, "Three", "Pentacles"),
  new Card(67, "Four", "Pentacles"),
  new Card(68, "Five", "Pentacles"),
  new Card(69, "Six", "Pentacles"),
  new Card(70, "Seven", "Pentacles"),
  new Card(71, "Eight", "Pentacles"),
  new Card(72, "Nine", "Pentacles"),
  new Card(73, "Ten", "Pentacles"),
  new Card(74, "Page", "Pentacles"),
  new Card(75, "Knight", "Pentacles"),
  new Card(76, "Queen", "Pentacles"),
  new Card(77, "King", "Pentacles"),
];
export default cards;
