type Pip =
  | "0 The Fool"
  | "I The Magician"
  | "II The High Priestess"
  | "III The Empress"
  | "IV The Emperor"
  | "V The Hierophant"
  | "VI The Lovers"
  | "VII The Chariot"
  | "VIII Strength"
  | "IX The Hermit"
  | "X The Wheel of Fortune"
  | "XI Justice"
  | "XII The Hanged Man"
  | "XIII Death"
  | "XIV Temperance"
  | "XV The Devil"
  | "XVI The Tower"
  | "XVII The Star"
  | "XVIII The Moon"
  | "XIX The Sun"
  | "XX Judgement"
  | "XXI The World"
  | "Ace"
  | "Two"
  | "Three"
  | "Four"
  | "Five"
  | "Six"
  | "Seven"
  | "Eight"
  | "Nine"
  | "Ten"
  | "Page"
  | "Knight"
  | "Queen"
  | "King";
export default Pip;
