name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push  Image
        run: |
          docker build . --tag ghcr.io/hannahellis4242/tarot-deck-service/tarot-deck-service:latest
          docker push ghcr.io/hannahellis4242/tarot-deck-service/tarot-deck-service:latest
